#!/usr/bin/env python3

import os, sys, subprocess, json

def shell(command):
	print(command)
	subprocess.Popen(command, shell=True).wait()

command = sys.argv[1] if len(sys.argv) > 1 else 'graphic'

src = [
	'main.cc',
	'hello_window.cc',
	'hello_triangle.cc'
]

obj = ['{}.o'.format(os.path.splitext(x)[0]) for x in src]

if command == 'graphic':
	build_age = os.path.getmtime('build')
	old = False
	for (s, o) in zip(src, obj):
		s_age = os.path.getmtime(s)
		o_age = os.path.getmtime(o)
		if not os.path.isfile(o) or s_age > o_age or build_age > o_age:
			old = True
			shell('x86_64-w64-mingw32-g++-posix -std=c++17 -Iinclude -c -o {} {}'.format(o, s))
	if (old):
		shell('x86_64-w64-mingw32-g++-posix {} -Llib -lglad -lglfw3 -lgdi32 -static-libstdc++ -static -lpthread -o graphic'.format(' '.join(obj)))
		try:
			os.renames('graphic.exe', 'graphic')
		except:
			pass
	else:
		print('up to date.')

if command == 'compile':
	cwd = os.getcwd()
	compile = []
	for file in src:
		compile.append({
			'directory': cwd,
			'arguments': ['-std=c++17', '-Iinclude'],
			'file': file
		})
	compile = json.dumps(compile, indent='\t')
	with open('compile_commands.json', 'w') as file:
		print(compile, file=file)
	print(compile)

if command == 'clean':
	shell('rm -f {}'.format(' '.join(obj)))
	shell('rm -f graphic')

if command == 'reset':
	shell('rm -f compile_commands.json')
	shell('rm -rf .cache')
